### ISSUE TITLE
this pulg-in can support the acquisition of browser tab audio?

### ISSUE THREAD

**Issue by Ksoeun** [botbahlul/crx-live-translate#2]
The microphone sometimes records some other sounds. Can this plug-in add the audio function of the current tab of chrome

**Comment by botbahlul** [comment]
> The microphone sometimes records some other sounds. Can this plug-in add the audio function of the current tab of chrome

the MAIN ISSUE here is the OS Sound Input/Output device

in WINDOWS you can choose to use Stereo Mix (for any normal Laptop/PC without HDMI Connection) or for BETTER RESULT using VIRTUAL AUDIO CABLE which can be used for any HDMI or non HDMI connected device (you can do googling to download and install it)

in LINUX I can't find any other virtual device that we can use except that pavucontrol (Pulse Audio Control in debian based distros)

AFAIK THERE'S NO ANY WAY IN WEBSKITSPEECHRECOGNITION API THAT CAN LISTEN ONLY ON SPECIFIC TAB :)
