### ISSUE TITLE
Didn't show translated subtitles

### ISSUE THREAD

**Issue by Titan87zs** [botbahlul/crx-live-translate#4]
When I turn on the extension, only the recognized text is shown, not the translated subtitles

https://github.com/botbahlul/crx-live-translate/assets/112701558/70eb2884-3c50-4523-a9da-d47d3514070c

**Comment by botbahlul** [comment]
It's working fine here
![image](https://github.com/botbahlul/crx-live-translate/assets/88623122/e462faf8-ef8d-43da-8910-f2a5fe54d9d7)

Is GOOGLE TRANSLATE SERVERS BANNED in your country?
Have you installed CORS UNBLOCK CHROME EXTENSION and ACTIVATE IT?

Another thing that I have to tell you is that WEBKITSPEECHRECOGNTION seems have PROBLEM with ENGLISH VOICE. Mostly it will STOP LISTENING AFTER ONE SENTENCE completed (runs fine with other languages). I my self have to turn that listening button to OFF and ON again every time it's stop listening.

You can try my other apps like https://github.com/botbahlul/pyvosklivesubtitle or others (see my Repositories page).

**Comment by botbahlul** [comment]
> When I turn on the extension, only the recognized text is shown, not the translated subtitles
> 
>  Desktop_2023.mp4

I think I've found the problem. It looks like their javascript sometimes blocks this extension. There's nothing we can do about it. It's their site, their rules.
If you watch on a streaming site that has no blocking javascript, this extension will run fine on any languages.

**Comment by Titan87zs** [comment]
> > When I turn on the extension, only the recognized text is shown, not the translated subtitles
> > Desktop_2023.mp4
> 
> I think I've found the problem. It looks like their javascript sometimes blocks this extension. There's nothing we can do about it. It's their site, their rules. If you watch on a streaming site that has no blocking javascript, this extension will run fine on any languages.

ummm, but this is a local mp4 file

**Comment by botbahlul** [comment]
> > > When I turn on the extension, only the recognized text is shown, not the translated subtitles
> > > Desktop_2023.mp4
> > 
> > 
> > I think I've found the problem. It looks like their javascript sometimes blocks this extension. There's nothing we can do about it. It's their site, their rules. If you watch on a streaming site that has no blocking javascript, this extension will run fine on any languages.
> 
> ummm, but this is a local mp4 file

AFAIK, in all browsers javascript was restricted to access local files

https://www.google.com/search?q=browser+restrict+javascript+for+local+file&oq=browser+restrict+javascript+for+local+file&aqs=chrome..69i57.15663j0j1&sourceid=chrome&ie=UTF-8

try to create a local http server on your PC, put that mp4 file on it, then run this extension on your local http server

https://www.google.com/search?q=how+to+create+local+http+server&sca_esv=559361602&sxsrf=AB5stBhZrvhBZup0TUUhKM7kgSBjhYlZGQ%3A1692803723956&ei=iyLmZILsOdOS4-EPg_qqkAs&oq=how+to+create+local+htt&gs_lp=Egxnd3Mtd2l6LXNlcnAiF2hvdyB0byBjcmVhdGUgbG9jYWwgaHR0KgIIADIFEAAYgAQyBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMggQABiKBRiGAzIIEAAYigUYhgMyCBAAGIoFGIYDSMxuUABYhGVwCHgBkAEBmAHLAqABgiWqAQgwLjI3LjMuMbgBA8gBAPgBAcICBxAjGIoFGCfCAgQQIxgnwgIIEAAYigUYkQLCAgsQLhiDARixAxiKBcICERAuGIAEGLEDGIMBGMcBGNEDwgILEAAYgAQYsQMYgwHCAgsQLhiABBixAxiDAcICBxAAGIoFGEPCAggQLhiABBixA8ICCxAAGIoFGLEDGJECwgIKEAAYigUYyQMYQ8ICCBAAGIoFGJIDwgINEAAYigUYsQMYgwEYQ8ICCxAAGIoFGLEDGIMBwgIFEC4YgATCAggQABiABBixA8ICCBAAGIAEGMsBwgIHECMYsQIYJ8ICBxAAGIAEGArCAg0QABiABBixAxiDARgKwgIKEAAYgAQYsQMYCsICCBAuGIAEGMsBwgILEC4YgwEYsQMYgATCAhcQLhiABBjLARiXBRjcBBjeBBjgBNgBAcICChAAGIAEGBQYhwLCAgcQIxiwAhgnwgIHEAAYDRiABMICCBAAGBYYHhgK4gMEGAAgQYgGAboGBggBEAEYFA&sclient=gws-wiz-serp
