### ISSUE TITLE
its dosen't work on macos

### ISSUE THREAD

**Issue by ghost** [botbahlul/crx-live-translate#5]
I've mimicked the tutorials on github and YouTube, and pretty much followed the steps in the demo, but I don't know if it's because stereo mixing can't be turned on for macs (or I don't know where the corresponding option to turn it on is on macs) or if the plugin itself isn't currently compatible with mac？

My configuration plan is：macos edge browser

**Comment by botbahlul** [comment]
I don't have Mac or its emulator, so I've never tried this on Mac.
But AFAIK, for MacOS you need SOUNDFLOWER app to route audio (like what VIRTUAL AUDIO CABLE did on Windows PC).
So install it on your MacOS first, then try to route the audio just like what VAC did on Windows.

Maybe this link can help you :
https://apple.stackexchange.com/questions/221980/os-x-route-audio-output-to-audio-input
