### ISSUE TITLE
Voice recognition works, translation doesn't

### ISSUE THREAD

**Issue by thericle** [botbahlul/crx-live-translate#6]
It's the same as this issue: https://github.com/botbahlul/crx-live-translate/issues/4

But there, it seemed that the reason was that JavaScript was blocked in local files. But I have also tried it on many other sites like YouTube and the same thing happens, only the original text is shown, but not the translation.

Google Translate is not banned in my country, since I use other extensions that use Google Translate API. I've also tried changing my DNS server, although I'm not sure if it makes sense.

It's a pity because the voice recognition is so accurate and translation is seemingly the "easy" part, but without it there is no point in using this extension, at least for my use case.

Any help would be appreciated.

**Comment by That-Ruben** [comment]
I just stumbled on this extension. I will be trying it out tomorrow. Although I'm looking to modify this so that the output is displayed in full screen. I don't need it overlayed on a video. 
Anyway, if I also run into an issue with the translation, I will let you know

**Comment by That-Ruben** [comment]
I had the same issue. Translation didn't work. However, I was able to 'fix' it by toggling the CORS blocking extension on and off again. Not 100% sure if that was the problem. 

Unfortunately, for Japanese translation, the lack of punctuation between sentences is a problem. I would try having the app automatically interject ".." whenever there is 1 second of silence. Because of how different Japanese is grammatically, compared to English, the lack of punctuation causes wild misinterpretation. 
The translation doesn't know where one sentence end and the other begins

**Comment by botbahlul** [comment]
> It's the same as this issue: #4
> 
> But there, it seemed that the reason was that JavaScript was blocked in local files. But I have also tried it on many other sites like YouTube and the same thing happens, only the original text is shown, but not the translation.
> 
> Google Translate is not banned in my country, since I use other extensions that use Google Translate API. I've also tried changing my DNS server, although I'm not sure if it makes sense.
> 
> It's a pity because the voice recognition is so accurate and translation is seemingly the "easy" part, but without it there is no point in using this extension, at least for my use case.
> 
> Any help would be appreciated.

Have you installed CORS UNBLOCK EXTENSION and TURN IT ON?
When turned on you will see that "C" letter on its icon

![image](https://github.com/botbahlul/crx-live-translate/assets/88623122/bb0c69ff-8337-460b-8caf-9b3ecbc8567b)

**Comment by botbahlul** [comment]
> I had the same issue. Translation didn't work. However, I was able to 'fix' it by toggling the CORS blocking extension on and off again. Not 100% sure if that was the problem.
> 
> Unfortunately, for Japanese translation, the lack of punctuation between sentences is a problem. I would try having the app automatically interject ".." whenever there is 1 second of silence. Because of how different Japanese is grammatically, compared to English, the lack of punctuation causes wild misinterpretation. The translation doesn't know where one sentence end and the other begins

The main problem of this WEBKITSPEECHRECOGNITION API is we can't change the PAUSE THRESHOLD
