### ISSUE TITLE
Excuse me

### ISSUE THREAD

**Issue by steven150201** [botbahlul/crx-live-translate#7]
The plugin was deployed according to the settings, but the browser did not display subtitles. What is the reason for this? Thank you!

**Comment by botbahlul** [comment]
> The plugin was deployed according to the settings, but the browser did not display subtitles. What is the reason for this? Thank you!

FIRST OF ALL PLEASE READ THAT README PAGE CAREFULLY!

you will need VIRTUAL AUDIO CABLE app to make this extension to work properly
![image](https://github.com/botbahlul/crx-live-translate/assets/88623122/f99be126-f488-4486-be16-91cef8fd45a2)

If you don't have it, you're still can use STEREO MIX recording device (in your windows Control Panel) but it won't be as best as using VAC

![image](https://github.com/botbahlul/crx-live-translate/assets/88623122/9aceadd3-14c5-4420-beb4-05f90f18a233)

Another thing you should do is installing CORS UNBLOCK Chrome Extension and ACTIVATE IT!

![image](https://github.com/botbahlul/crx-live-translate/assets/88623122/765cb26c-d072-43ee-a1ec-7e6fb1188a52)
