### ISSUE TITLE
Translation API not working

### ISSUE THREAD

**Issue by trans-id** [botbahlul/crx-live-translate#8]
Due to restrictions in my country, access to the Google API is unavailable. As such, I am seeking alternative translation APIs, such as Microsoft or others. While the voice recognition functionality is satisfactory, I require translation capabilities. I kindly request you to share any suitable options available.

**Comment by botbahlul** [comment]
> Due to restrictions in my country, access to the Google API is unavailable. As such, I am seeking alternative translation APIs, such as Microsoft or others. While the voice recognition functionality is satisfactory, I require translation capabilities. I kindly request you to share any suitable options available.

You can try to use VPN to avoid the restriction.
Until now I'm still can't find any other FREE TRANSLATE API other than Google Translate API.
Have you installed and TURNED ON that CORS UNBLOCK EXTENSION?
After installed, PIN that extension into Chrome toolbar, then just click it to turn it on.
After turned on its icon will show that "C" letter.
![image](https://github.com/botbahlul/crx-live-translate/assets/88623122/64cefe2c-6c34-44db-847f-bcaa4ed8bee7)
