### ISSUE TITLE
`Show Timestamps` option doesn't work for Chinese language

### ISSUE THREAD

**Issue by pilgrimlyieu** [botbahlul/crx-live-translate#9]
![1](https://github.com/user-attachments/assets/55ea5789-59cc-4570-8107-c0de0fc5ffae)
![2](https://github.com/user-attachments/assets/54d59dbf-7454-432a-951d-fdb34918e9d8)

**Comment by botbahlul** [comment]
> ![1](https://private-user-images.githubusercontent.com/80107081/349032147-55ea5789-59cc-4570-8107-c0de0fc5ffae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjQ5MjYsIm5iZiI6MTcyMTQ2NDYyNiwicGF0aCI6Ii84MDEwNzA4MS8zNDkwMzIxNDctNTVlYTU3ODktNTljYy00NTcwLTgxMDctYzBkZTBmYzVmZmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA4MzcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Y2FkZjI1ZGQ3OGQwYWZmMTBlZDZmMmY4MzliYzc2ZGE0NmYyMjNlZDcwNTQ1MDAwZGNkNjYxOTlkNTA4MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MD1ANBwpd4C5PZ9i9HGfFBJ_xnnIq6vCVo4jT-VBQ6k) ![2](https://private-user-images.githubusercontent.com/80107081/349032163-54d59dbf-7454-432a-951d-fdb34918e9d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjQ5MjYsIm5iZiI6MTcyMTQ2NDYyNiwicGF0aCI6Ii84MDEwNzA4MS8zNDkwMzIxNjMtNTRkNTlkYmYtNzQ1NC00MzJhLTk1MWQtZmRiMzQ5MThlOWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA4MzcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYmRjYzU0MjM5YTQyMDY3YTQyZGQ1OTljYjI5NGQxOTRjNTQ3NjY3NGJlZWE4MzM4MGU5NTBhNGY5NTgzZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TD-SdKUI6U2f9LPTZ9KUFZFeUapDlZWI8odL0fN5KwQ)

Thanks!

Your feedback has pointed me to a lot of bugs when dealing with Chinese language.

Please check the update and let me know if you're still find any bugs.

**Comment by pilgrimlyieu** [comment]
![img](https://github.com/user-attachments/assets/8d7f5c7f-429f-4d56-8060-93c05405e3f7)

Thanks! It works now. I'll open a new thread if I encounter new issue.
